/*
Ethereal Farm
Copyright (C) 2020  Lode Vandevenne

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/


// headers for leaves for seasons
var leaves_spring_header = 'q:#484 g:#6a6 G:#8f8 Q:#afa';
var leaves_summer_header = 'q:#040 g:#080 G:#0b0 Q:#0f0';
var leaves_autumn_header = 'q:#f30 g:#f70 G:#fa0 Q:#fe0';
var leaves_winter_header = 'q:#88f g:#aaf G:#ccf Q:#eef';
var leaves_ethereal_header = 'q:#bb8 g:#dda G:#ffa Q:#ffe';

var stem_metal_header0 = 'ho:#999';
var stem_metal_header1 = 'ho:#f00';
var stem_metal_header2 = 'ho:#fff';
var stem_metal_header3 = 'ho:#dfb';
var stem_metal_header4 = 'ho:#ff0';
var stem_metal_header5 = 'X:#fff O:#eee o:#ddd x:#ccc';
var stem_metal_header6 = 'X:#fee O:#ecc o:#dbb x:#caa';
var stem_metal_header7 = 'X:#fff O:#eef o:#ddf x:#ccf';
var stem_metal_header8 = 'X:#fff O:#efe o:#dfd x:#cfc';
var stem_metal_header9 = 'X:#fff O:#fee o:#fdd x:#fcc';
var stem_metal_header10 = 'X:#fff O:#ffe o:#ffd x:#ffc';


// the images have season dependent palette, for colors qgGQ. Use them as green, but they'll become season dependent. Only those 4 colors.
function createTreeImages(name, top, bottom, opt_stem_header) {
  var s = (opt_stem_header ? (' ' + opt_stem_header) : '') + '\n';
  var a0 = generateImageCanvas('#' + leaves_spring_header + s + top.trim());
  var a1 = generateImageCanvas('#' + leaves_summer_header + s + top.trim());
  var a2 = generateImageCanvas('#' + leaves_autumn_header + s + top.trim());
  var a3 = generateImageCanvas('#' + leaves_winter_header + s + top.trim());
  var a4 = generateImageCanvas('#' + leaves_ethereal_header + s + top.trim());
  var b0 = generateImageCanvas('#' + leaves_spring_header + s + bottom.trim());
  var b1 = generateImageCanvas('#' + leaves_summer_header + s + bottom.trim());
  var b2 = generateImageCanvas('#' + leaves_autumn_header + s + bottom.trim());
  var b3 = generateImageCanvas('#' + leaves_winter_header + s + bottom.trim());
  var b4 = generateImageCanvas('#' + leaves_ethereal_header + s + bottom.trim());
  return [name, [a0, a1, a2, a3, a4], [b0, b1, b2, b3, b4]];
}


var image_metal_tree_top = `
................
.........QQQ....
....QQG..QGGg...
....QGgq.QGgqq..
..Q.Ogq..Xgqqx..
.QGG.OOoXOoqox..
.QGggqXOooo.ox..
.QGgqXOoOoq.ox..
.QGgqOOoOoo.QQ..
.XqqqOoo.OoQQGg.
.XOo.OoGGOoQGgqq
QQOo.QoGqOoQGqq.
QGOoQGGq.Oo.qqx.
QGOoQGgq.Oo.ox..
..OOQGqqoooox...
...OOqqOoxxx....
`;

var image_metal_tree_stem = `
......XOox......
......XOox......
......XOox......
......XOox......
......XOox......
......XOox......
......XOox......
.....XOOoxx.....
.....XOOoxx.....
....XOOOoxxx....
................
................
................
................
................
................
`;


// includes name for each stage
var tree_images = [
// tree level 0
createTreeImages('weathered tree', `
................
................
................
................
................
................
............x...
....x.o..x..x...
....x.ox.x0x....
.o...x.x..x..0..
.o..o.x..x0.0...
..o.o.x.x.0.0...
...o..x.x.00....
....oox.x00.....
.....ooxx0......
.....ooxx0......
`,`
.....ooxx0......
..G..o0xx0......
.Gg..0o0x0......
...o.o0xx0......
....oooxx0......
.....ooxx0......
....oooxx00.....
...ooxooxx00....
..ooxxxooxx00...
................
................
................
................
................
................
................
`),
createTreeImages('young sprout', `
................
................
................
................
................
................
................
................
................
....Q...Qg......
...Qg...gq.Qg...
....q...o..Qq...
.....o.oo..xx...
......oo..xx....
......ooxx......
.......ox.......
`,`
.......ox.......
.......ox.......
.......ox.......
.......xo.......
.......ox.......
.......ox.......
.......oo.......
.......ox.......
......ooxx......
................
................
................
................
................
................
................
`),
createTreeImages('young sprout', `
................
................
................
................
................
................
................
................
...QQ..QGg......
..QGgq.QGq.QQg..
..QGgq..qq.Qgq..
....q...o..Qqq..
.....o.oo..xx...
......oo..xx....
......ooxx......
.......ox.......
`,`
.......ox.......
.......ox.......
.......ox.......
.......xo.......
.......ox.......
.......ox.......
.......oo.......
.......ox.......
......ooxx......
................
................
................
................
................
................
................
`),
createTreeImages('young sprout', `
................
................
................
................
................
................
........Qg......
...QQ..QGg..Qg..
..QQgq.QGq.QGgq.
..QGgq.QGq.QGgq.
..QGgq..qq.Qgq..
....q...o..Qqq..
.....o.oo..xx...
......oo..xx....
......ooxx......
.......ox.......
`,`
.......ox.......
.......ox.......
.......ox.......
.......xo.......
.......ox.......
.......ox.......
.......oo.......
.......ox.......
......ooxx......
................
................
................
................
................
................
................
`),
createTreeImages('young tree', `
................
................
................
................
................
...QG...........
..QGg..QGg..QG..
..Ggg..QGg..QG..
...go.QGgg.QGGg.
..QGg.QGgq.GGgq.
..Ggq..gq..Ggq..
....o..o...Gqq..
....o..o...xx...
.....ooo..xx....
......ooxx......
......oox.......
`,`
......oox.......
......oox.......
......oox.......
......oxo.......
......oox.......
......oox.......
......ooo.......
......ooo.......
......oox.......
.....oooxx......
................
................
................
................
................
................
`),
createTreeImages('young tree', `
................
................
................
....QQgg........
...QGGggQQQgg...
..QGGggQQGGgQG..
..GGGgQQGGgQQGg.
...GgqQQGgqQGGg.
..QGgqQGgqqQGgq.
..Ggq..gqq.Ggq..
...oo..oo..Gqq..
....oo.oo..xx...
.....oooo.xx....
......ooxxx.....
......ooxx......
......oox.......
`,`
......oox.......
......oox.......
......oox.......
......oxo.......
......oox.......
......oox.......
......ooo.......
......ooo.......
......oox.......
.....oooxx......
................
................
................
................
................
................
`),
createTreeImages('adult tree', `
................
................
....QQQ.QQQQ....
...QQGggQGGGg...
..QGGGggGGGggG..
..QGGggQGGGgQG..
.QGGGgQGGGgQQGg.
.QGGgqQGGgqQGGg.
.QGGgqQGgqqQGgq.
.QGgqq.gqqGGgq..
...ooq.oo.GGqq..
...ooo.oo..xxx..
....ooooo.xxx...
.....ooooxxx....
......oooxx.....
......oooxx.....
`,`
......ooxx......
......ooxx......
......ooox......
......ooox......
......ooox......
......ooxx......
......ooxx......
......ooox......
.....ooooxx.....
....oooooxxx....
................
................
................
................
................
................
`),
createTreeImages('adult tree', `
................
........Q.......
....QQQQGQQQ....
...QGQGGGGGgq...
..QGgGGQQgggqq..
..QGggQgGqgqqq..
.QQgGgGGgGqqQQG.
.QGGGqQGggqQGGg.
.QGggqQgGqqQGgg.
.QGGgqqGqqQgggq.
..Ggqq.gqQGggq..
..ooo..oxqQgqq..
...ooo.ox..xxx..
....oooox.xxx...
.....oooxxxx....
......ooxxx.....
`,`
......ooxx......
......ooxx......
......ooox......
......ooox......
......ooox......
......ooxx......
......ooxx......
......ooox......
.....ooooxx.....
....oooooxxx....
................
................
................
................
................
................
`),
createTreeImages('adult tree', `
................
........G.......
..QGGQQggQgQ....
.QGgGgGGgGGgggq.
QGggQGGGQggggqg.
QgGGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq..oxqQGgqq.
.Qqqqo.ox..xxq..
....oooox.xxx...
.....oooxxxx....
......ooxxx.....
`,`
......ooxx......
......ooxx......
......ooox......
......ooox......
......ooox......
......ooxx......
......ooxx......
......ooox......
.....ooooxx.....
....oooooxxx....
................
................
................
................
................
................
`),
createTreeImages('adult tree', `
................
...QQ...G...Qg..
..QGGQQggQgQggq.
.QGgGgGGgGGgggq.
QGggQGGGQgggqqg.
QgGGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq..oxqQGgqq.
.Qqqqo.ox..xxq..
....oooQg.xxx...
.....oogqxxx....
......ooxxx.....
`,`
......ooxxx.....
......ooxxx.....
......ooxxx.....
......xooxx.....
......oxoxx.....
......xooxx.....
......ooxxx.....
.....oooxxx.....
....ooxooxxx....
...ooxxxoxxxx...
................
................
................
................
................
................
`),
createTreeImages('large tree', `
................
......QQQGG.....
...GGQgGgQgQ.g..
.QGgGgGGgGGQQgq.
QGggQGGGQggggqg.
QgGGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq.ox.qQGgqq.
.Qqqq.ox.ox.xq..
..oox.oQgqx.xx..
...ooxQGgqxxx...
....oooqqxxx....
`,`
.....oooxxx.....
.....oooxxx.....
.....oooxxx.....
.....oxooxx.....
.....xoxoxx.....
.....oxooxx.....
.....oooxxx.....
....ooooxxx.....
...oooxooxxx....
..oooxxxoxxxx...
................
................
................
................
................
................
`),
createTreeImages('grand tree', `
..QQG.......QQ..
.QGgg.QQQGGQQGG.
.GgGgqgGgQgQGGGq
.GqgqgGGgGGQGGqq
QGgqqGGGQggggqq.
GqqGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq.ox.qQGgqq.
.QQqq.ox.ox.QQQ.
QQGgx.oQgqxQQGG.
QGGgqxQGgqxxGGgq
..qqqooqqxxxgqq.
`,`
.Q...oooxxx.....
QGg..oooxxx.....
Ggqoooooxxx.....
.q..ooxooxx.....
.....xoxoxx.....
.....oxooxx.....
.....oooxxx.....
....ooooxxx.....
...oooxooxxx....
..oooxxxoxxxx...
................
................
................
................
................
................
`),
createTreeImages('curly tree', `
....Q...........
..Qgg.QQQG...QQ.
.QgGgqgGgQgGQGGq
.QqgqQGGgGGQGGqq
QGgqQGGGQQGggqq.
GqqQgGGQGqGGQGG.
QGGggGGqgGgGgGgq
.GgQGGgQggGGgGgq
QGGGQgqqGqqGGggq
QggGggqGQqQGgggq
.gGQQqqgqGGGGgqq
..ggq.ox.qQGgqq.
.QQQq.ox.ox.QQQ.
.QGgx.oQgqxQQGG.
.GGgqxQGgqxxGGgq
..qqqooqqxxxgqq.
`,`
.Q...xoooxxx....
QGg...xoooxx....
Ggqooxoooxx.....
.q..ooooxx......
.....xoooxx.....
......xoooxx....
.....xoooxxx....
....ooooxxx.....
...oooxooxxx....
..oooxxxoxxxx...
................
................
................
................
................
................
`),
createTreeImages('hollow tree', `
..QQG.......QQ..
.QGgg.QQQGGQQGG.
.GgGgqgGgQgQGGGq
.GqgqgGGgGGQGGqq
QGgqqGGGQggggqq.
GqqGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq.ox.qQGgqq.
.QQqq.ox.ox.QQQ.
QQGgx.oQgqxQQGG.
QGGgqxQGgqxxGGgq
..qqqooqqxxxgqq.
`,`
.Q...oooxxxx....
QGg.oooxxxxxx...
Ggqooox..oxxx...
.q..ox....oxx...
...oox....oxx...
...ooxx..oxx....
....ooxooxx.....
....ooooxxx.....
...oooxooxxx....
..oooxxxoxxxx...
................
................
................
................
................
................
`),
createTreeImages('zinc tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header0),
createTreeImages('bronze tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header1),
createTreeImages('silver tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header2),
createTreeImages('electrum tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header3),
createTreeImages('gold tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header4),
createTreeImages('platinum tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header5),
createTreeImages('rhodium tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header6),
createTreeImages('sapphire tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header7),
createTreeImages('emerald tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header8),
createTreeImages('ruby tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header9),
createTreeImages('diamond tree', image_metal_tree_top, image_metal_tree_stem, stem_metal_header10),
createTreeImages('magnificent tree', `
................
......QQQGG.....
...GGQgGgQgQ.g..
.QGgGgGGgGGQQgq.
QGggQGGGQggggqg.
QgGGggQgGqQqQQG.
QGGggQGGgGqQGGgq
QGgGGqgGggQGgGgq
QGGGQgggGqqGGggq
QggGggqGqqQGgggq
.GGgggqgqQGGGgqq
.Qggq.ox.qQGgqq.
.Qqqq.ox.ox.xq..
..oox.oQgqx.xx..
...ooxQGgqxxx...
....oooqqxxx....
`,`
.Q...oooxxx.....
QGg..oooxxx.....
Ggqoooooxxx.....
.q..ooxooxx.....
.....xoxoxx.....
.....oxooxx.....
.....oooxxx.....
....ooooxxx.....
...oooxooxxx....
..oooxxxoxxxx...
................
................
................
................
................
................
`),
];




