/*
Ethereal Farm
Copyright (C) 2020-2023  Lode Vandevenne

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/


var image_missingfish = createFishImage(
`
................
................
................
.........$$.....
.......$$$......
.......$$.....$.
....$$$$$$$..$$.
...$$$$$$$$$$$$.
..$$0$$$$$$$$$$.
.$$$$$$$$$$$$$$.
.$$$$$$$$$$$.$$.
..$$$$$$$$$...$.
....$$$$$$......
......$$........
.......$$.......
........$$......
`);

var image_goldfish0 = createFishImage(`
+:#fb8a X:#fb8 O:#d96
................
.......+++......
.......++++.....
.......+++++....
......XXO+++...+
....XZXOXOX+.+++
...XZ0ZXOXOXO+++
..XXXZXOXOXOO+..
..XXOXOXOXOOO...
...OXOXOXOOOO+..
....OOOOOO++.++.
......OOO.++.+++
......++......++
......+++.......
.......++.......
................
`);

var image_goldfish1 = createFishImage(`
+:#f63a X:#fb8 O:#d96
................
.......+++......
.......++++.....
.......+++++....
......PPR+++...+
....PZPRPRP+.+++
...PZ0ZPRPRPR+++
..PPPZPRPRPRR+..
..PPRPRPRPRRR...
...RPRPRPRRRR+..
....RRRRRR++.++.
......RRR.++.+++
......++......++
......+++.......
.......++.......
................
`);

var image_koi0 = createFishImage(`
................
................
................
................
................
9......999......
99..9$$$999999..
.999999999$$909.
.9999$$$99$$$9$9
99.9$$$$$9999999
9........9.99..9
........9..9....
................
................
................
................
`);

var image_koi1 = createFishImage(`
................
................
................
................
................
P......PPP......
PP..P333PPPPPP..
.PPPPPPPPP33P0P.
.PPPP333PP333P3P
PP.P33333PPPPPPP
P........P.PP..P
........P..P....
................
................
................
................
`);

var image_octopus0 = createFishImage(`
aa:#d33
......999N......
....99NNNNNN....
...9NNNNNNNNN...
...9NNNNNNNNN...
..9NNNNNNNNNNN..
..NN90NNNN90NM..
..NN00NNNN00NM..
..NNNNNNNNNNNM..
...NNN0NN0NNM...
...NNNN00NNNM...
.NNNNNNNNNMMMNN.
.NM.NNNMMMNN.NM.
....NM.NN.NM....
....NM.NM.NM....
.......NM.......
................
`);

var image_anemone0 = createFishImage(`
...........9....
..9........M....
..NM..9...NN....
...M..N...M....9
.9.N..MM..MN...M
.N.N...N...N.Mmm
MM.MM..NM.MM.M..
N...N...M.N..m.9
NM..NMM.N.N.Mm.M
.M....N.N.M.M.mm
.NN...N.M.M.m.M.
..M..MMXXXMMm.M.
..MNNMXXOXXMmmm.
....MMMXXXMmMM..
......MMMmmm....
................
`);

var image_anemone1 = createFishImage(`
...........p....
..p........R....
..PR..p...PP....
...R..P...R....p
.p.P..RR..RP...R
.P.P...P...P.Rrr
RR.RR..PR.RR.R..
P...P...R.P..r.0
PR..PRR.P.P.Rr.R
.R....P.P.R.R.rr
.PP...P.R.R.r.R.
..R..RRZZZRRr.R.
..RPPRZZzZZRrrr.
....RRRZZZRrRR..
......RRRrrr....
................
`);

var image_shrimp0 = createFishImage(`
.......ssssss...
.............s..
.....sssssss..s.
....s.......s.s.
......s$$$$..s..
.....$s$$$0$s...
....$$s$$$$$....
....$$Ss$$......
...$$Ss..s......
...s$S.s..s.....
...$sss.........
...$S...........
...$Sss.........
...SS...........
....ss..........
................
`);

var image_puffer0 = createFishImage(`
......X.........
......X..X......
....X.XXXX.X....
....XXOOOOXX....
..XXOOOOoOOOXX..
...XOoOOOOOOX...
XXXO0OOO0OoOoXXX
.XXOOOOOOOOooXX.
88847000OOO66888
8887770777466888
...8747476668...
..887777464688..
....88476688....
....8.8888.8....
......8..8......
.........8......
`);

var image_puffer1 = createFishImage(`
.........P......
......P..P......
....P.PPPP.P....
....PPRRrrPP....
..PPRRrRRRRRPP..
...PRRRRRrRRP...
PPPRxRrRxRRRrPPP
.PPRRRRRRRrRRPP.
88847xxxRRR66888
888777x777664888
...8777476468...
..887477766688..
....88746688....
....8.8888.8....
......8..8......
.........8......
`);


var image_eel0 = createFishImage(`
................
.........$$$&&&.
.......$$$a&&900
.....$$$aa&&000.
....$$aa&000....
...$$a&&00......
...$a&&0........
...$a&&.........
...$a&&&........
....$&&&&.......
....$$&&&&......
.....$$&&00.....
..$$$aa&&00.....
.$$aa00000......
.0000...........
................
`);


// red eel
var image_eel1 = createFishImage(`
................
.........XXXrrr.
.......XXXRrr9pp
.....XXXRRrrppp.
....XXRRrppp....
...XXRrrpp......
...XRrrp........
...XRrr.........
...XRrrr........
....Xrrrr.......
....XXrrrr......
.....XXrrpp.....
..XXXRRrrpp.....
.XXRRppppp......
.pppp...........
................
`);

// yellow tang
var image_tang0 = createFishImage(`h0y:#dc0 h1y:#ff4 h0l:#cd0 h1l:#ef4
................
................
.....KLKKLKK....
....KLKKLKKLK...
....ZZZZZZZKK...
...Z0YYYYYYKL...
..Z0Y0YYYYYYK..K
..ZY0YYYYYYYy.LL
ZZYYYKKYYYYYYyKK
.ZYYLLLYYYYYyyLL
ZZYYYKKYYYYyK.KK
...yYYYYYyyyL..K
....yyyyyyyKK...
......KLKKLKK...
........LKKL....
................
`);

// red tang
var image_tang1 = createFishImage(`
+:#e66
................
................
.....+0++0++....
....+0++0++0+...
....RRRRRRR++...
...R0rrrrrr+0...
..R0r0rrrrrr+..+
..Rr0rrrrrrrp.00
RRrrr++rrrrrrp++
.Rrr000rrrrrpp00
RRrrr++rrrrp+.++
...prrrrrppp0..+
....ppppppp++...
......+0++0++...
........0++0....
................
`);

// leporinus
var image_leporinus0 = createFishImage(`
................
................
................
........R.......
........Rr......
r.......RrR.....
Rr....22Z22ZZZ..
.Rr22Z00--00-0-.
..--00-00-00--yy
.rR-00-00-00yyy.
rR.y00y00y00....
R.......RrR.....
........Rr......
........R.......
................
................
`);
