/*
Ethereal Farm
Copyright (C) 2020-2023  Lode Vandevenne

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// The images for the tower defense challenges and its pests

var image_burrow = generateImageCanvas(`
................
................
................
................
......xxx.......
....xx0000......
...x0000xxo.....
...x00xxxxxo....
..x00xxxxxxxo...
..x00xxxxxxxo...
..x0xxxxxxxo....
...xxxxxxxo.....
....oooooo......
................
................
................
`);


// generates 4 rotated versions: N, E, S, W
function createPestImages(image) {
  var a = generateImageCanvas(image);
  image = rot90(image);
  var b = generateImageCanvas(image);
  image = rot90(image);
  var c = generateImageCanvas(image);
  image = rot90(image);
  var d = generateImageCanvas(image);
  return [a, b, c, d];
}

var images_ant = createPestImages(`
...2........2...
...2........2...
....22.22.22....
..2...2222...2..
..2...0220...2..
...2..2222..2...
....22.22.22....
......2222......
...2220220222...
..2...2002...2..
....22.22.22....
...2..2222..2...
..2..022220..2..
..2..200002..2..
......2222......
.......22.......
`);


var images_tick = createPestImages(`
................
o.0.o......o.0.o
.000..o.0.o.000.
oxxxo..000.oxxxo
.xxx..oxxxo.xxx.
.o.o...xxx..o.o.
o...o..o.o.o...o
......o...o.....
.o.0.o..........
..000..o.0.o....
.oxxxo..000o.0.o
..xxx..oxxx.000.
..o.o...xxxoxxxo
.o...o..o.ooxxx.
.......o...oo.o.
...........o...o
`);
